/* =========================================================
   Cold2Hot · Landing Page
   ========================================================= */
(() => {
  "use strict";

  const $ = (sel, ctx = document) => ctx.querySelector(sel);
  const $$ = (sel, ctx = document) => [...ctx.querySelectorAll(sel)];

  /* ---------------------------------------------------------
     i18n (US18). El español vive en el HTML; aquí solo el inglés.
     --------------------------------------------------------- */
  const EN = {
    "nav.problem": "Problem",
    "nav.solution": "Solution",
    "nav.how": "How it works",
    "nav.roi": "ROI calculator",
    "nav.plans": "Pricing",
    "nav.team": "Team",
    "nav.cta": "Request a demo",
    "nav.login": "Log in",

    "hero.eyebrow": "IoT for last-mile delivery",
    "hero.title": 'Every order arrives <span class="grad-text">as good as it left</span> your kitchen.',
    "hero.lead": "Cold2Hot is the smart delivery box that keeps food at the right temperature, only opens with an OTP code and records proof of every delivery. Fewer complaints, zero tampering and full traceability.",
    "hero.cta_app": "Try live platform 🚀",
    "hero.cta1": "Request a demo",
    "hero.cta2": "Calculate your savings →",
    "hero.check1": "Cold / hot profiles",
    "hero.check2": "OTP unlock via Bluetooth",
    "hero.check3": "Delivery photo",

    "mock.shipment": "Shipment",
    "mock.hot": "Hot profile",
    "mock.inrange": "In range",
    "mock.lock": "Lock",
    "mock.locked": "Locked",
    "mock.battery": "Battery",
    "mock.link": "Link",
    "mock.alertTitle": "Lid not fully closed",
    "mock.alertBody": "Preventive warning · order inside",

    "metrics.m1": "fewer temperature complaints",
    "metrics.m2": "of deliveries with no tampering incidents",
    "metrics.m3": "fewer logistics disputes",
    "metrics.m4": "customer retention",
    "metrics.note": "Impact targets defined in the Cold2Hot Lean UX Canvas.",

    "problem.eyebrow": "The problem",
    "problem.title": "The last mile is where quality… and trust get lost",
    "problem.lead": "Passive backpacks and boxes can't react to traffic, distance or weather. And when a customer complains, nobody has proof of what happened along the way.",
    "problem.c1t": "Food at the wrong temperature",
    "problem.c1d": "On trips over 15 minutes, hot food arrives lukewarm and cold food thaws. Static insulation, no active control.",
    "problem.c2t": "Tampered orders",
    "problem.c2d": "Zippers, velcro and stickers can be opened or replicated. There's no way to know if the order was opened en route.",
    "problem.c3t": "Disputes without evidence",
    "problem.c3d": "Refunds, false non-delivery claims and unfair penalties for couriers due to the lack of an auditable record.",

    "solution.eyebrow": "The solution",
    "solution.title": "A smart box, an app for couriers and a dashboard for your operation",
    "solution.lead": "Cold2Hot combines IoT hardware, a mobile app and a web platform to secure the thermal and physical chain of custody of every order.",
    "feat.f1t": "Active thermal regulation",
    "feat.f1d": "Assign the cold or hot profile from the dashboard at dispatch. The DS18B20 sensor (±0.5 °C) reports temperature every minute.",
    "feat.f2t": "OTP code unlock",
    "feat.f2d": "A solenoid lock keeps the box closed until the courier enters the one-time code generated by the restaurant in the app.",
    "feat.f3t": "Two-level security",
    "feat.f3d": "A magnetic and an infrared sensor tell a poorly closed lid (preventive warning) apart from a real removal of the order (critical alert).",
    "feat.f4t": "Photo evidence",
    "feat.f4d": "Couriers close every delivery with a photo linked to the shipment. It protects both the restaurant and the courier.",
    "feat.f5t": "Real-time monitoring",
    "feat.f5d": "Dashboard with temperature, battery and lock status for every active box, plus instant push and web alerts.",
    "feat.f6t": "Immutable audit trail",
    "feat.f6d": "A single report with the trip's temperature curve, exact opening time and delivery photo to settle any complaint.",

    "how.eyebrow": "How it works",
    "how.title": "From dispatch to the door in four steps",
    "how.s1t": "Create the shipment",
    "how.s1d": "Register the order in the web dashboard, pick the thermal profile and an OTP code is generated.",
    "how.s2t": "The box protects the order",
    "how.s2d": "The SmartBox regulates temperature, locks itself and streams telemetry throughout the route.",
    "how.s3t": "Unlock at destination",
    "how.s3d": "The courier connects via Bluetooth from the app and enters the OTP to release the lock.",
    "how.s4t": "Delivery with proof",
    "how.s4d": "Delivery photo, cycle closed and audit report instantly available in the dashboard.",

    "seg.eyebrow": "Who it's for",
    "seg.title": "Built for the people who move delivery",
    "seg.s1tag": "Web dashboard",
    "seg.s1t": "Delivery operations managers",
    "seg.s1d": "Restaurants and chains with high dispatch volume that need to cut refunds and protect their brand.",
    "seg.s1l1": "Create shipments and assign thermal profiles",
    "seg.s1l2": "Monitor boxes, battery and alerts live",
    "seg.s1l3": "Audit deliveries with charts, timestamps and photos",
    "seg.s1l4": "Manage your couriers and devices",
    "seg.s1btn": "Open web dashboard ›",
    "seg.s2tag": "Mobile app",
    "seg.s2t": "Delivery couriers",
    "seg.s2d": "Motorbike or bicycle couriers, freelance or on payroll, who want to work without unfair penalties.",
    "seg.s2l1": "Guided Bluetooth pairing with the box",
    "seg.s2l2": "OTP unlock in seconds",
    "seg.s2l3": "Warnings if the lid wasn't closed properly",
    "seg.s2l4": "Proof of delivery with a photo",

    "roi.eyebrow": "ROI calculator",
    "roi.title": "How much is cold food costing you today?",
    "roi.lead": "Enter your current orders and complaints. We estimate your annual savings using the target reduction of 35% in complaints and 70% in tampering disputes.",
    "roi.orders": "Delivery orders per month",
    "roi.claims": "Temperature complaints per month",
    "roi.disputes": "Tampering / non-delivery disputes per month",
    "roi.ticket": "Average ticket (S/)",
    "roi.boxes": "Cold2Hot boxes in your fleet",
    "roi.saving": "Estimated net savings per year",
    "roi.loss": "Current loss from complaints and disputes",
    "roi.recovered": "Losses you avoid",
    "roi.cost": "Cold2Hot subscription",
    "roi.rate": "Current complaint rate",
    "roi.cta": "See pricing",

    "cmp.eyebrow": "Comparison",
    "cmp.title": "The best of industrial telemetry, at a restaurant's price",
    "cmp.passive": "Passive thermal backpack",
    "cmp.industrial": "Industrial telemetry",
    "cmp.r1": "Active thermal control",
    "cmp.r2": "Real-time monitoring",
    "cmp.r3": "Physical lock with OTP",
    "cmp.r4": "Tampering detection",
    "cmp.r5": "Delivery photo (Proof of Delivery)",
    "cmp.r6": "Courier app",
    "cmp.r7": "Built for food delivery",
    "cmp.r8": "Affordable for SMBs",

    "hw.eyebrow": "Inside the SmartBox",
    "hw.title": "Open, reliable hardware ready for the street",
    "hw.h1t": "Microcontroller",
    "hw.h1d": "ESP32 NodeMCU with Wi-Fi and Bluetooth Low Energy for telemetry and lock control.",
    "hw.h2t": "Temperature sensor",
    "hw.h2d": "Range from −55 °C to +125 °C with ±0.5 °C accuracy inside the compartment.",
    "hw.h3t": "Two-level security",
    "hw.h3d": "Magnetic lid sensor plus infrared package-presence sensor to avoid false alarms.",
    "hw.h4t": "Solenoid lock",
    "hw.h4d": "Mechanical lock that only releases with a valid OTP code.",
    "hw.h5t": "Works without signal",
    "hw.h5d": "An edge node with a local database stores records when coverage drops and syncs them later.",

    "plans.eyebrow": "Pricing",
    "plans.title": "Pay per active box, no million-dollar licenses",
    "plans.lead": "Monthly subscription to the monitoring and audit software, sized to your fleet.",
    "plans.perbox": "/ box per month",
    "plans.contact": "Contact sales",
    "plans.popular": "Most popular",
    "plans.custom": "Custom",
    "plans.p1d": "For restaurants starting their own delivery.",
    "plans.p1l1": "Up to 5 boxes",
    "plans.p1l2": "Real-time temperature monitoring",
    "plans.p1l3": "OTP unlock and delivery photo",
    "plans.p1l4": "30-day history",
    "plans.p2d": "For chains with their own or outsourced fleet.",
    "plans.p2l1": "6 to 25 boxes",
    "plans.p2l2": "Everything in Starter",
    "plans.p2l3": "Critical tampering alerts",
    "plans.p2l4": "Courier analytics",
    "plans.p2l5": "12-month history",
    "plans.p3d": "For multi-location operations and delivery platforms.",
    "plans.p3l1": "More than 25 boxes",
    "plans.p3l2": "Everything in Pro",
    "plans.p3l3": "API integration",
    "plans.p3l4": "Dedicated support and SLA",
    "plans.note": "Reference prices in Peruvian soles, excluding VAT (IGV) and SmartBox hardware.",

    "team.eyebrow": "About us",
    "team.title": "We are IoTeam",
    "team.lead": "A startup of Software Engineering students at UPC with one mission: every order should arrive as good as it left the restaurant.",
    "team.mission": "Mission",
    "team.missionD": "Make every food order arrive as good as it left the restaurant, protecting its temperature and security all the way.",
    "team.vision": "Vision",
    "team.visionD": "Become a Latin American benchmark in IoT technology for food delivery, helping restaurants and couriers work with more confidence.",
    "team.r1": "Market & strategy",
    "team.r2": "Architecture & backend",
    "team.r3": "Full-stack & DDD",
    "team.r4": "Product & Lean UX",
    "team.r5": "Backend, web & mobile",
    "team.r6": "Telemetry & security",
    "team.r7": "IoT & needfinding",

    "contact.title": "Take your delivery to the next level",
    "contact.lead": "Book a demo with a real SmartBox and see how Cold2Hot protects your orders end to end.",
    "contact.web": "Go to the Web App →",
    "contact.mobile": "Get the courier app →",
    "contact.name": "Name",
    "contact.business": "Restaurant or company",
    "contact.email": "Email",
    "contact.plan": "Plan of interest",
    "contact.submit": "Request a demo",

    "footer.tagline": "A product by IoTeam · Universidad Peruana de Ciencias Aplicadas",
    "footer.contact": "Contact",
    "footer.rights": "All rights reserved."
  };

  // Textos generados por JS
  const MSG = {
    es: {
      payback: (x) => `Por cada S/ 1 de suscripción recuperas S/ ${x}.`,
      noGain: "Con estos valores la suscripción aún supera las pérdidas evitadas. Prueba con menos cajas o contáctanos para un plan a medida.",
      empty: "Ingresa tus datos para estimar el ahorro.",
      formError: "Completa todos los campos con un correo válido.",
      formOk: (name) => `¡Gracias, ${name}! Te contactaremos en menos de 24 horas para agendar tu demo.`,
      title: "Cold2Hot · Cajas de delivery inteligentes | IoTeam"
    },
    en: {
      payback: (x) => `For every S/ 1 of subscription you recover S/ ${x}.`,
      noGain: "With these values the subscription still exceeds the avoided losses. Try fewer boxes or contact us for a custom plan.",
      empty: "Enter your data to estimate your savings.",
      formError: "Please fill in every field with a valid email.",
      formOk: (name) => `Thanks, ${name}! We'll reach out within 24 hours to schedule your demo.`,
      title: "Cold2Hot · Smart delivery boxes | IoTeam"
    }
  };

  const i18nNodes = $$("[data-i18n]");
  const ES = new Map(i18nNodes.map((el) => [el, el.innerHTML]));
  let lang = "es";

  function setLang(next) {
    lang = next === "en" ? "en" : "es";
    i18nNodes.forEach((el) => {
      el.innerHTML = lang === "en" ? (EN[el.dataset.i18n] ?? ES.get(el)) : ES.get(el);
    });
    document.documentElement.lang = lang;
    document.title = MSG[lang].title;
    $$(".lang__btn").forEach((b) => b.classList.toggle("is-active", b.dataset.lang === lang));
    try { localStorage.setItem("c2h-lang", lang); } catch (_) { /* almacenamiento no disponible */ }
    updateROI();
  }

  $$(".lang__btn").forEach((btn) => btn.addEventListener("click", () => setLang(btn.dataset.lang)));

  /* ---------------------------------------------------------
     Navbar: sombra al hacer scroll, menú móvil y link activo
     --------------------------------------------------------- */
  const navbar = $("#navbar");
  const nav = $("#nav");
  const menuToggle = $("#menuToggle");

  const onScroll = () => navbar.classList.toggle("is-scrolled", window.scrollY > 8);
  window.addEventListener("scroll", onScroll, { passive: true });
  onScroll();

  menuToggle.addEventListener("click", () => {
    const open = nav.classList.toggle("is-open");
    menuToggle.setAttribute("aria-expanded", String(open));
  });
  $$("a", nav).forEach((a) => a.addEventListener("click", () => {
    nav.classList.remove("is-open");
    menuToggle.setAttribute("aria-expanded", "false");
  }));

  const navLinks = $$("a[href^='#']", nav);
  const sectionObserver = new IntersectionObserver((entries) => {
    entries.forEach((entry) => {
      if (!entry.isIntersecting) return;
      navLinks.forEach((a) => a.classList.toggle("is-active", a.getAttribute("href") === `#${entry.target.id}`));
    });
  }, { rootMargin: "-45% 0px -50% 0px" });
  navLinks.forEach((a) => {
    const section = $(a.getAttribute("href"));
    if (section) sectionObserver.observe(section);
  });

  /* ---------------------------------------------------------
     Animaciones de entrada y contadores
     --------------------------------------------------------- */
  const reduceMotion = window.matchMedia("(prefers-reduced-motion: reduce)").matches;

  const revealObserver = new IntersectionObserver((entries, obs) => {
    entries.forEach((entry) => {
      if (!entry.isIntersecting) return;
      entry.target.classList.add("is-visible");
      obs.unobserve(entry.target);
    });
  }, { threshold: 0.12 });
  $$(".reveal").forEach((el, i) => {
    el.style.transitionDelay = `${(i % 4) * 70}ms`;
    revealObserver.observe(el);
  });

  function animateCounter(el) {
    const target = Number(el.dataset.target);
    if (reduceMotion) { el.textContent = target; return; }
    const start = performance.now();
    const duration = 1400;
    const tick = (now) => {
      const p = Math.min((now - start) / duration, 1);
      el.textContent = Math.round(target * (1 - Math.pow(1 - p, 3)));
      if (p < 1) requestAnimationFrame(tick);
    };
    requestAnimationFrame(tick);
  }
  const counterObserver = new IntersectionObserver((entries, obs) => {
    entries.forEach((entry) => {
      if (!entry.isIntersecting) return;
      animateCounter(entry.target);
      obs.unobserve(entry.target);
    });
  }, { threshold: 0.5 });
  $$(".counter").forEach((el) => counterObserver.observe(el));

  /* ---------------------------------------------------------
     Mock de telemetría en el hero (perfil caliente 60–75 °C)
     --------------------------------------------------------- */
  const spark = { line: $("#sparkLine"), area: $("#sparkArea"), temp: $("#mockTemp") };
  const POINTS = 30, W = 300, H = 80, T_MIN = 60, T_MAX = 76;
  const readings = [];
  let t = 68;
  const nextReading = () => {
    t += (Math.random() - 0.5) * 1.6 + (68 - t) * 0.12;
    return Math.min(74, Math.max(62, t));
  };
  for (let i = 0; i < POINTS; i++) readings.push(nextReading());

  function drawSpark() {
    const step = W / (POINTS - 1);
    const y = (v) => H - ((v - T_MIN) / (T_MAX - T_MIN)) * H;
    const d = readings.map((v, i) => `${i ? "L" : "M"}${(i * step).toFixed(1)},${y(v).toFixed(1)}`).join(" ");
    spark.line.setAttribute("d", d);
    spark.area.setAttribute("d", `${d} L${W},${H} L0,${H} Z`);
    spark.temp.textContent = readings[readings.length - 1].toFixed(1);
  }
  drawSpark();
  if (!reduceMotion) {
    setInterval(() => {
      readings.shift();
      readings.push(nextReading());
      drawSpark();
    }, 1500);
  }

  /* ---------------------------------------------------------
     Calculadora de ROI (US01)
     --------------------------------------------------------- */
  const CLAIM_REDUCTION = 0.35;   // Lean UX: -35% reclamos por temperatura
  const DISPUTE_REDUCTION = 0.70; // Lean UX: -70% disputas logísticas

  // Precio por caja según el plan que correspondería a la flota
  const pricePerBox = (boxes) => (boxes <= 5 ? 49 : boxes <= 25 ? 39 : 35);

  const roi = {
    orders: $("#roiOrders"),
    claims: $("#roiClaims"),
    disputes: $("#roiDisputes"),
    ticket: $("#roiTicket"),
    boxes: $("#roiBoxes"),
    net: $("#roiNet"),
    loss: $("#roiLoss"),
    recovered: $("#roiRecovered"),
    cost: $("#roiCost"),
    rate: $("#roiRate"),
    bar: $("#roiBar"),
    payback: $("#roiPayback")
  };

  const money = (n) => {
    const locale = lang === "en" ? "en-US" : "es-PE";
    const sign = n < 0 ? "−" : "";
    return `${sign}S/ ${Math.abs(Math.round(n)).toLocaleString(locale)}`;
  };
  const num = (input) => {
    const v = parseFloat(input.value);
    const valid = Number.isFinite(v) && v >= 0;
    input.classList.toggle("is-invalid", input.value !== "" && !valid);
    return valid ? v : 0;
  };

  function updateROI() {
    const orders = num(roi.orders);
    const claims = num(roi.claims);
    const disputes = num(roi.disputes);
    const ticket = num(roi.ticket);
    const boxes = Math.max(1, Math.round(num(roi.boxes)));

    const loss = (claims + disputes) * ticket * 12;
    const recovered = (claims * CLAIM_REDUCTION + disputes * DISPUTE_REDUCTION) * ticket * 12;
    const cost = boxes * pricePerBox(boxes) * 12;
    const net = recovered - cost;
    const rate = orders > 0 ? ((claims + disputes) / orders) * 100 : 0;

    roi.loss.textContent = money(loss);
    roi.recovered.textContent = money(recovered);
    roi.cost.textContent = `−${money(cost)}`;
    roi.net.textContent = money(net);
    roi.net.style.color = net >= 0 ? "" : "#ffa184";
    roi.rate.textContent = `${rate.toFixed(1)}%`;
    roi.bar.style.width = `${loss > 0 ? Math.min(100, (recovered / loss) * 100) : 0}%`;

    if (loss === 0) roi.payback.textContent = MSG[lang].empty;
    else if (net < 0) roi.payback.textContent = MSG[lang].noGain;
    else roi.payback.textContent = MSG[lang].payback((recovered / cost).toFixed(1));
  }

  $("#roiForm").addEventListener("input", updateROI);
  $("#roiForm").addEventListener("submit", (e) => e.preventDefault());

  /* ---------------------------------------------------------
     Planes → precarga el plan en el formulario de contacto (US02)
     --------------------------------------------------------- */
  const planSelect = $("#contactPlan");
  $$("[data-plan]").forEach((btn) => btn.addEventListener("click", () => {
    planSelect.value = btn.dataset.plan;
  }));

  /* ---------------------------------------------------------
     Formulario de contacto (sin backend: valida y confirma)
     --------------------------------------------------------- */
  const form = $("#contactForm");
  const formMsg = $("#formMsg");
  form.addEventListener("submit", (e) => {
    e.preventDefault();
    const fields = $$("input", form);
    let ok = true;
    fields.forEach((f) => {
      const valid = f.checkValidity() && f.value.trim() !== "";
      f.classList.toggle("is-invalid", !valid);
      ok = ok && valid;
    });
    formMsg.className = "form-msg";
    if (!ok) {
      formMsg.textContent = MSG[lang].formError;
      formMsg.classList.add("is-error");
      return;
    }
    const name = form.elements.name.value.trim().split(" ")[0];
    const ctaText = lang === "en" ? "Launch Interactive Web App ➜" : "Probar Plataforma Web en Vivo ➜";
    formMsg.innerHTML = `
      <div style="display:flex; flex-direction:column; gap:8px;">
        <span>${MSG[lang].formOk(name)}</span>
        <a href="${APP_URL}" target="_blank" class="btn btn--hot btn--sm" style="align-self:flex-start; margin-top:6px; text-decoration:none;">
          ${ctaText}
        </a>
      </div>
    `;
    formMsg.classList.add("is-ok");
    form.reset();
    planSelect.value = "Pro";
  });

  /* ---------------------------------------------------------
     Enrutamiento dinámico hacia la Aplicación Web (cold2hot-web-app)
     --------------------------------------------------------- */
  const isLocal = window.location.hostname === "localhost" || 
                  window.location.hostname === "127.0.0.1" || 
                  window.location.protocol === "file:";
  const APP_URL = isLocal ? "http://localhost:4200" : "https://cold2hot-web-app.vercel.app";

  $$(".btn-app-link").forEach((btn) => {
    btn.href = APP_URL;
  });

  /* ---------------------------------------------------------
     Init
     --------------------------------------------------------- */
  $("#year").textContent = new Date().getFullYear();

  let saved = null;
  try { saved = localStorage.getItem("c2h-lang"); } catch (_) { /* almacenamiento no disponible */ }
  if (saved === "en") setLang("en");
  else updateROI();
})();
